Вместо этого файла после запуска на исполнение кода из файла 1_prepare_database_100000.py должен
сформироваться файл датасета dataset_100000_pbc.db. 
